#!/bin/sh


###############################################################
# PBS part
###############################################################

# Assigns a job name
#PBS -N calc_stats

# Assigns the queue
#PBS -q eternity

# PBS -l nodes=1:ppn=1
# PBS -l host=radegast-local

#Join option
# PBS -j oe
# PBS -M d.korda@seznam.cz

# Sends mail to the user when the job begins, ends, aborts.
# PBS -m a

#PBS -o /nfshome/david/Contours/log/default_calc_stats.out
#PBS -e /nfshome/david/Contours/log/default_calc_stats.err

#PBS -V
PBS_O_WORKDIR="${WD}"

# Redirect output and error files to specific files after PBS_JOBID is set
# output_file="${LD}/${PBS_JOBID}_calc_stats.out"
# error_file="${LD}/${PBS_JOBID}_calc_stats.err"

# Redirect stdout and stderr to the desired files
# exec > "$output_file" 2> "$error_file"

##############################################################
# Execution
##############################################################
# Move to the directory where the Python script is located
cd "${PBS_O_WORKDIR}" || exit

export MPLBACKEND="Agg"

# Run the Python script
./run_calc_stats_bin ${SETTINGS} 2>&1 | tee "${LD}/${PBS_JOBID}_calc_stats.log"
